@dynamic_prompt_system
Feature: dynamic_prompt_system
    As a general public member
    I want to know the advice on how to handle the missing person given their physical traits as well as mental and health condition
    So that I can have the most appropriate way to handle the missing person with minimum discruption and unwanted incidence

Background: 
    Given I am on "Post Detail" page for a particular post
    Then I should see "Commonly Asked Questions" section

@happy_path
Scenario: User click to see first answer generated by dynamic prompt system
    Given I am logged in as general public
    And I am on Post Detail page for missing person name "David"
    And I click on the "Question one" button in "Commonly Asked Questions" section
    Then I should see correct answer

@happy_path
Scenario: User click to see second answer generated by dynamic prompt system
    Given I am logged in as general public
    And I am on Post Detail page for missing person name "David"
    And I click on the "Question two" button in "Commonly Asked Questions" section
    Then I should see correct answer

@happy_path
Scenario: User click to see second answer generated by dynamic prompt system
    Given I am logged in as general public
    And I am on Post Detail page for missing person name "David"
    And I click on the "Question three" button in "Commonly Asked Questions" section
    Then I should see correct answer

